export const presta = [
  {
    id: 1,
    name: "Naissance",
    description: "Immortalisez les premiers sourires de vos bébés.",
    price: "À partir de 180€",
    src: "/naissance.png",
    info: "Afin de s'adapter au besoin de bébé, il faut compter 2 à 3h pour une séance.",
    forfait1: ["Séance bébé seul & parents", "180€", "10 photos"],
    forfait2: ["Séance bébé seul & parents", "230€", "15 photos"],
    restriction: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Je me déplace chez vous, avec du matériel (paniers, duvets, coussins, linges ...) et des décors.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport.",
      "Vous en voulez toujours plus ? Vous avez la possibilité d'ajouter des photos à 10€ l'unité.",
      "Les photos seront disponibles en HD dans un délai de 3 semaines via un lien de téléchargement.",
    ],
  },
  {
    id: 2,
    name: "Grossesse",
    description: "Gardez des souvenirs inoubliables de votre grossesse.",
    price: "À partir de 150€",
    src: "/grossesse.png",
    info: "La séance se déroule en intérieur ou en extérieur selon vos envies.",
    forfait1: ["Forfait 1", "150€", "10 photos"],
    forfait2: ["Forfait 2", "200€", "15 photos"],
    restriction: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Nous avons la possibilité d'aller le long de la mer au coucher ou au lever du soleil pour un supplément de 30€.",
      "Je propose 3 robes de grossesse (crème, rouille et rose poudré) en complément de 15€.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport (hors séance bord de mer).",
      "Il est possible d'ajouter des photos à 10€ l'unité.",
      "Les photos seront disponibles en HD dans un délai de 3 semaines via un lien de téléchargement.",
    ],
  },
  {
    id: 3,
    name: "Couple, famille, solo",
    description: "Figez les moments de vie de façon authentique et naturelle.",
    price: "À partir de 150€",
    src: "/couple.png",
    info: "La séance se réalise en intérieur ou en extérieur, selon vos envies (et parfois la saison).",
    forfait1: ["Forfait 1", "150€", "10 photos"],
    forfait2: ["Forfait 2", "200€", "15 photos"],
    restriction: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport.",
      "Il faut compter environ 1h / 1h30 pour une séance.",
      "Vous en souhaitez davantage ? Il est possible d'ajouter des photos à 10€ l'unité.",
      "Les photos seront disponibles en HD dans un délai de 3 semaines via un lien de téléchargement.",
    ],
  },
  {
    id: 4,
    name: "Animaux de compagnie",
    description:
      "Parce que nos boules de poils ont le droit aussi à leur séance photo !",
    price: "À partir de 90€",
    src: "/animaux.png",
    info: "Pour nos amis poilus et leurs parents !",
    forfait1: ["Forfait 1", "90€", "5 photos"],
    forfait2: ["Forfait 2", "150€", "10 photos"],
    restriction: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Il faut compter environ 1h / 1h30 pour une séance.",
      "La séance peut se réaliser en intérieur ou en extérieur.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport.",
      "Vous n'en avez pas assez ? Il est possible d'ajouter des photos à 10€ l'unité.",
      "Les photos seront disponibles en HD dans un délai de 3 semaines via un lien de téléchargement.",
    ],
  },
  {
    id: 5,
    name: "Baptême",
    description: "Capturez les moments précieux de vos enfants.",
    price: "À partir de 350€, devis sur mesure",
    src: "/bapteme.png",
    info: "Pour les baptêmes ou les anniversaires.",
    forfait1: ["Séance 3H", "350€", "65 photos"],
    forfait2: ["Séance 4H", "500€", "85 photos"],
    contact: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport.",
      "Possibilité de choisir la galerie complète en complément de 200€.",
      "Les photos seront disponibles en HD dans un délai de 3 semaines via un lien de téléchargement.",
      "Pour toute autre demande, n'hésitez pas à me contacter.",
    ],
  },
  {
    id: 6,
    name: "Mariage",
    description: 'Tout simplement car c\'est le "Plus beau jour de votre vie".',
    price: "À partir de 600€, devis sur mesure",
    src: "/mariage.png",
    info: "Pour votre mariage, je viendrai vous rencontrer avant le grand jour, afin de répondre au mieux à vos souhaits.",
    forfait1: ["Mairie, lieu de culte, et vin d'honneur", "600€", "95 photos"],
    forfait2: ["Journée complète*", "900€", "photos illimitées"],
    contact: [
      "*préparation de la mariée, mairie, lieu de culte, et vin d'honneur",
      "Si vous souhaitez que je reste jusqu'à la pièce montée il faudra compter un supplément de 200€.",
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport.",
      "Les photos seront disponibles en HD dans un délai de 1 mois. Elles seront envoyées sur une clé USB directement à votre domicile.",
      "Pour toute autre demande, n'hésitez pas à me contacter.",
    ],
  },
  {
    id: 7,
    name: "Les séances Boudoir",
    description:
      "Pour le plaisir de se faire plaisir ! Osez une séance Boudoir pour révéler votre beauté.",
    price: "À partir de 150€",
    src: "/boudoir.png",
    forfait1: ["Forfait 1", "150€", "10 photos"],
    forfait2: ["Forfait 2", "200€", "15 photos"],
    info: "La séance se réalise en intérieur, pour garder toute l'intimité de ce moment. Nous échangeons quelques temps avant de commencer la séance. La séance boudoir offre un moment de temps suspendu et de déconnexion. Elle met en valeur le corps humain à travers des jeux de lumières.",
    restriction: [
      "Le prix comprend la retouche artistique et le traitement des photos.",
      "Pour des séances au-delà de 20km d'Amiens, un supplément sera facturé pour les frais de transport.",
      "Il faut compter environ 1h30 pour une séance.",
      "Les photos seront disponibles en HD dans un délai de 3 semaines via un lien de téléchargement.",
    ],
  },
  {
    id: 8,
    name: "Portrait professionnel",
    description:
      "Je vous accompagne et vous guide afin d'obtenir des portraits authentiques pour vos expériences professionnelles.",
    price: "(Devis personnalisé)",
    src: "/portrait.png",
    contact: [
      "Avant de réaliser la séance il est important que nous échangions par rapport à vos attentes et votre métier.",
      "Un devis personnalisé vous sera proposé après cet entretien.",
      "Je vous invite à remplir le formulaire de contact pour que je puisse en savoir plus.",
    ],
  },
  {
    id: 9,
    name: "Photographie culinaire",
    description: "Mise en valeur de votre entreprise et de vos réalisations. ",
    price: "(Devis personnalisé)",
    src: "/culinaire.png",
    contact: [
      "Les tarifs se font sur devis après un entretien téléphonique. Cela permet de répondre au mieux a vos attentes.",
      "Je vous invite à remplir le formulaire de contact. ",
    ],
  },
];
